# DEPRECATE path to executables or their parent directories
# calicost_dir: "/u/congma/ragr-data/users/congma/Codes/CalicoST/"
# eagledir: "/u/congma/ragr-data/users/congma/environments/Eagle_v2.4.1/"

# NB path to 1K SNP definition for conditional calling
region_vcf: "/u/congma/ragr-data/users/congma/references/snplist/genome1K.phase3.SNP_AF5e4.chr1toX.hg38.vcf.gz"
phasing_panel: "/u/congma/ragr-data/users/congma/references/phasing_ref/1000G_hg38/"

# NB path to Visium 10x read-depth-ratio output
spaceranger_dir: "/u/congma/ragr-data/datasets/DingLab/HT112/U1/"

# Qs what are these?
geneticmap_file: "/u/congma/ragr-data/datasets/genetic_map/recomb-hg38/genetic_map_GRCh38_merged.tab"
hgtable_file: "/u/congma/ragr-data/users/congma/Codes/STARCH_crazydev/hgTables_hg38_gencode.txt"
filtergenelist_file: "/n/fs/ragr-data/users/congma/references/cellranger_refdata-gex-GRCh38-2020-A/genes/ig_gene_list.txt"
filterregion_file: "/n/fs/ragr-data/users/congma/references/cellranger_refdata-gex-GRCh38-2020-A/genes/HLA_regions.bed"
tumorprop_file: "/u/congma/ragr-data/datasets/DingLab/HT112/HT112C1-T1_U1/ht112_u1_rctd_prop.tsv"

# output allele matrices required by CalicoST and 
output_snpinfo: "/u/congma/ragr-data/users/congma/Datasets/test_calico/snpinfo"
outputdir_calicost: "/u/congma/ragr-data/users/congma/Datasets/test_calico/calicost"

# runtime parameters
samtools_sorting_mem: "4G" # (only used when jointly calling from multiple slices)

# cellsnp-lite
UMItag: "Auto"
cellTAG: "CB"
nthreads_cellsnplite: 64

# Eagle phasing
chromosomes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

# CalicoST parameters
random_state: [0, 1, 2, 3, 4]
np_threshold: 1.0
