name: calicost
channels:
  - bioconda
  - conda-forge
  - defaults
  - schmidt73
dependencies:
  - python>=3.8
  - conda-libmamba-solver==23.11.0
  - bzip2==1.0.8
  - numpy==1.24.4
  - scipy==1.11.3
  - pandas==2.1.1
  - scikit-learn==1.3.2
  - scanpy==1.9.6
  - anndata==0.10.3
  - numba==0.57.1
  - tqdm==4.66.1
  - statsmodels==0.14.0
  - networkx==3.2.1
  - pysam==0.22.0
  - cellsnp-lite=1.2.3
  - startle
  - ete3
  
