# path to executables or their parent directories
calicost_dir: 
cellsnplite: "cellsnp-lite"
samtools: "samtools"
bgzip: "bgzip"
tabix: "tabix"
eagledir: "/u/congma/ragr-data/users/congma/environments/Eagle_v2.4.1/"

# running parameters
# samtools sort (only used when joingly calling from multiple slices)
samtools_sorting_mem: "4G"
# cellsnp-lite
UMItag: "Auto"
cellTAG: "CB"
nthreads_cellsnplite: 20
region_vcf: 
# Eagle phasing
phasing_panel: 
chromosomes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

# input
bamlist: "bamfile_list.tsv"

# CalicoST parameters
random_state: [0, 1, 2, 3, 4]
geneticmap_file: "resources/genetic_map_GRCh38_merged.tab"
hgtable_file: "resources/hgTables_hg38_gencode.txt"
filtergenelist_file: "resources/ig_gene_list.txt"
filterregion_file: "resources/HLA_regions.bed"
tumorprop_file: "estimate_tumor_prop/loh_estimator_tumor_prop.tsv"
maxspots_pooling: 19
t: 1-1e-4
n_states: 7
n_clones: 5
secondary_min_umi: 400

# output
output_snpinfo: "snpinfo"
outputdir_calicost: "calicost"
